[mypy]

python_version = 3.11
warn_return_any = True
warn_unused_configs = True
disallow_untyped_defs = True
disallow_incomplete_defs = True
check_untyped_defs = True
strict_optional = True
warn_redundant_casts = True
warn_unused_ignores = True

# Ignore les erreurs pour les tests
[mypy-tests.*]
ignore_errors = True

# Ignore les erreurs pour les lib externes
[mypy-numba.*]
ignore_missing_imports = True

[mypy-scipy.*]
ignore_missing_imports = True

[mypy-tqdm.*]
ignore_missing_imports = True